export default {
  sunset: require("../icons/temp.svg").default,
  sunrise: require("../icons/temp.svg").default,
  humidity: require("../icons/humidity.svg").default,
  wind: require("../icons/wind.svg").default,
  pressure: require("../icons/pressure.svg").default,
  "01d": require("../icons/sunny.svg").default,
  "01n": require("../icons/night.svg").default,
  "02d": require("../icons/day.svg").default,
  "02n": require("../icons/cloudy-night.svg").default,
  "03d": require("../icons/cloudy.svg").default,
  "03n": require("../icons/cloudy.svg").default,
  "04d": require("../icons/perfect-day.svg").default,
  "04n": require("../icons/cloudy-night.svg").default,
  "09d": require("../icons/rain.svg").default,
  "09n": require("../icons/rain-night.svg").default,
  "10d": require("../icons/rain.svg").default,
  "10n": require("../icons/rain-night.svg").default,
  "11d": require("../icons/storm.svg").default,
  "11n": require("../icons/storm.svg").default,
};
